# Copyright (c) 2024 Beijing Institute of Open Source Chip (BOSC)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2 or later, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

obj-$(CONFIG_APP_HELLO) += hello.o
obj-$(CONFIG_APP_DEVICES) += devices.o
obj-$(CONFIG_APP_LS) += ls.o
obj-$(CONFIG_APP_DEVMEM) += devmm.o
obj-$(CONFIG_APP_HISTORY) += history.o
obj-$(CONFIG_APP_DMA_TEST) += dma_test.o
obj-$(CONFIG_APP_DMA_TEST_EXT) += dma_test_ext.o
obj-$(CONFIG_APP_MEM_READ) += mem_read.o
obj-$(CONFIG_APP_IMSIC_TEST) += imsic_test.o
obj-$(CONFIG_APP_VS_IMSIC_MULTI_TEST) += vs_imsic_multi_test.o
obj-$(CONFIG_APP_SPINLOCK_TEST) += spinlock_test.o
obj-$(CONFIG_APP_VCPU_RUN) += vcpu_run.o
obj-$(CONFIG_APP_VCPU_RUN_EXT) += vcpu_run_ext.o
obj-$(CONFIG_APP_VCPU_INFO) += vcpu_info.o
obj-$(CONFIG_APP_USER_RUN) += user_run.o
obj-$(CONFIG_APP_PAGE_TLB_TEST) += page_tlb_test.o
obj-$(CONFIG_APP_TASK_INFO) += task_info.o
obj-$(CONFIG_APP_CSR_CTL) += csr_ctl.o
obj-$(CONFIG_APP_PLIC_SET_AFFINITY) += plic_set_affinity.o
obj-$(CONFIG_APP_STREAM) += stream.o
obj-$(CONFIG_APP_HUGE_PAGE_TEST) += huge_page_test.o
obj-$(CONFIG_APP_TINY_TEST) += tiny_test.o
obj-$(CONFIG_APP_PLANE) += plane/
obj-$(CONFIG_APP_GET_PTE_TEST) += get_pte_test.o
obj-$(CONFIG_APP_SVNAPOT_TEST) += svnapot_test.o
obj-$(CONFIG_MULTICORE_TEST) += multicore/
obj-$(CONFIG_APP_FLOAT_TEST) += float_test.o
obj-$(CONFIG_APP_MEM_WALK) += mem_walk.o
obj-$(CONFIG_APP_STVAL) += stval.o
obj-$(CONFIG_APP_CMD_LOADER) += cmd_loader.o
obj-$(CONFIG_APP_MEM_TESTER) += mem_tester.o
obj-$(CONFIG_APP_G_STAGE_TEST) += g_stage.o
obj-$(CONFIG_APP_SVPBMT_TEST) += svpbmt_test.o
