# Copyright (c) 2024 Beijing Institute of Open Source Chip (BOSC)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2 or later, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

obj-y += uart/
obj-y += irq/
obj-y += timer/
obj-y += iommu/
obj-y += dma-mapping/
obj-y += dmac/
obj-y += task/
obj-y += devicetree/
obj-y += device_driver.o
obj-y += event.o
obj-y += cpu.o
obj-y += percpu.o
obj-y += clock.o
obj-y += pci_device_driver.o
obj-y += stub.o
