#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__

#define PT_SIZE 296		/* sizeof(struct pt_regs) */
#define PT_SEPC 0		/* offsetof(struct pt_regs, sepc) */
#define PT_RA 8			/* offsetof(struct pt_regs, ra) */
#define PT_FP 64		/* offsetof(struct pt_regs, s0) */
#define PT_S0 64		/* offsetof(struct pt_regs, s0) */
#define PT_S1 72		/* offsetof(struct pt_regs, s1) */
#define PT_S2 144		/* offsetof(struct pt_regs, s2) */
#define PT_S3 152		/* offsetof(struct pt_regs, s3) */
#define PT_S4 160		/* offsetof(struct pt_regs, s4) */
#define PT_S5 168		/* offsetof(struct pt_regs, s5) */
#define PT_S6 176		/* offsetof(struct pt_regs, s6) */
#define PT_S7 184		/* offsetof(struct pt_regs, s7) */
#define PT_S8 192		/* offsetof(struct pt_regs, s8) */
#define PT_S9 200		/* offsetof(struct pt_regs, s9) */
#define PT_S10 208		/* offsetof(struct pt_regs, s10) */
#define PT_S11 216		/* offsetof(struct pt_regs, s11) */
#define PT_SP 16		/* offsetof(struct pt_regs, sp) */
#define PT_TP 32		/* offsetof(struct pt_regs, tp) */
#define PT_A0 80		/* offsetof(struct pt_regs, a0) */
#define PT_A1 88		/* offsetof(struct pt_regs, a1) */
#define PT_A2 96		/* offsetof(struct pt_regs, a2) */
#define PT_A3 104		/* offsetof(struct pt_regs, a3) */
#define PT_A4 112		/* offsetof(struct pt_regs, a4) */
#define PT_A5 120		/* offsetof(struct pt_regs, a5) */
#define PT_A6 128		/* offsetof(struct pt_regs, a6) */
#define PT_A7 136		/* offsetof(struct pt_regs, a7) */
#define PT_T0 40		/* offsetof(struct pt_regs, t0) */
#define PT_T1 48		/* offsetof(struct pt_regs, t1) */
#define PT_T2 56		/* offsetof(struct pt_regs, t2) */
#define PT_T3 224		/* offsetof(struct pt_regs, t3) */
#define PT_T4 232		/* offsetof(struct pt_regs, t4) */
#define PT_T5 240		/* offsetof(struct pt_regs, t5) */
#define PT_T6 248		/* offsetof(struct pt_regs, t6) */
#define PT_GP 24		/* offsetof(struct pt_regs, gp) */
#define PT_ORIG_A0 280		/* offsetof(struct pt_regs, orig_a0) */
#define PT_SSTATUS 256		/* offsetof(struct pt_regs, sstatus) */
#define PT_SBADADDR 264		/* offsetof(struct pt_regs, sbadaddr) */
#define PT_SCAUSE 272		/* offsetof(struct pt_regs, scause) */
#define PT_HSTATUS 280		/* offsetof(struct pt_regs, hstatus) */
#define PT_SATP 288		/* offsetof(struct pt_regs, satp) */

#define VIRT_CPU_HOST_ZERO 0	/* offsetof(struct cpu_context, host_context.zero) */
#define VIRT_CPU_HOST_RA   8	/* offsetof(struct cpu_context, host_context.ra) */
#define VIRT_CPU_HOST_SP   16	/* offsetof(struct cpu_context, host_context.sp) */
#define VIRT_CPU_HOST_GP   24	/* offsetof(struct cpu_context, host_context.gp) */
#define VIRT_CPU_HOST_TP   32	/* offsetof(struct cpu_context, host_context.tp) */
#define VIRT_CPU_HOST_T0   40	/* offsetof(struct cpu_context, host_context.t0) */
#define VIRT_CPU_HOST_T1   48	/* offsetof(struct cpu_context, host_context.t1) */
#define VIRT_CPU_HOST_T2   56	/* offsetof(struct cpu_context, host_context.t2) */
#define VIRT_CPU_HOST_S0   64	/* offsetof(struct cpu_context, host_context.s0) */
#define VIRT_CPU_HOST_S1   72	/* offsetof(struct cpu_context, host_context.s1) */
#define VIRT_CPU_HOST_A0   80	/* offsetof(struct cpu_context, host_context.s2) */
#define VIRT_CPU_HOST_A1   88	/* offsetof(struct cpu_context, host_context.a1) */
#define VIRT_CPU_HOST_A2   96	/* offsetof(struct cpu_context, host_context.a2) */
#define VIRT_CPU_HOST_A3   104	/* offsetof(struct cpu_context, host_context.a3) */
#define VIRT_CPU_HOST_A4   112	/* offsetof(struct cpu_context, host_context.a4) */
#define VIRT_CPU_HOST_A5   120	/* offsetof(struct cpu_context, host_context.a5) */
#define VIRT_CPU_HOST_A6   128	/* offsetof(struct cpu_context, host_context.a6) */
#define VIRT_CPU_HOST_A7   136	/* offsetof(struct cpu_context, host_context.a6) */
#define VIRT_CPU_HOST_S2   144	/* offsetof(struct cpu_context, host_context.s2) */
#define VIRT_CPU_HOST_S3   152	/* offsetof(struct cpu_context, host_context.s3) */
#define VIRT_CPU_HOST_S4   160	/* offsetof(struct cpu_context, host_context.s4) */
#define VIRT_CPU_HOST_S5   168	/* offsetof(struct cpu_context, host_context.s5) */
#define VIRT_CPU_HOST_S6   176	/* offsetof(struct cpu_context, host_context.s6) */
#define VIRT_CPU_HOST_S7   184	/* offsetof(struct cpu_context, host_context.s7) */
#define VIRT_CPU_HOST_S8   192	/* offsetof(struct cpu_context, host_context.s8) */
#define VIRT_CPU_HOST_S9   200	/* offsetof(struct cpu_context, host_context.s9) */
#define VIRT_CPU_HOST_S10  208	/* offsetof(struct cpu_context, host_context.s10) */
#define VIRT_CPU_HOST_S11  216	/* offsetof(struct cpu_context, host_context.s11) */
#define VIRT_CPU_HOST_T3   224	/* offsetof(struct cpu_context, host_context.t3) */
#define VIRT_CPU_HOST_T4   232	/* offsetof(struct cpu_context, host_context.t4) */
#define VIRT_CPU_HOST_T5   240	/* offsetof(struct cpu_context, host_context.t5) */
#define VIRT_CPU_HOST_T6   248	/* offsetof(struct cpu_context, host_context.t6) */
#define VIRT_CPU_HOST_SEPC    256	/* offsetof(struct cpu_context, host_context.sepc) */
#define VIRT_CPU_HOST_SSTATUS 264	/* offsetof(struct cpu_context, host_context.sstatus) */
#define VIRT_CPU_HOST_HSTATUS 272	/* offsetof(struct cpu_context, host_context.hstatus) */

#define VIRT_CPU_GUEST_ZERO 280	/* offsetof(struct cpu_context, guest_context.zero) */
#define VIRT_CPU_GUEST_RA   288	/* offsetof(struct cpu_context, guest_context.ra) */
#define VIRT_CPU_GUEST_SP   296	/* offsetof(struct cpu_context, guest_context.sp) */
#define VIRT_CPU_GUEST_GP   304	/* offsetof(struct cpu_context, guest_context.gp) */
#define VIRT_CPU_GUEST_TP   312	/* offsetof(struct cpu_context, guest_context.tp) */
#define VIRT_CPU_GUEST_T0   320	/* offsetof(struct cpu_context, guest_context.t0) */
#define VIRT_CPU_GUEST_T1   328	/* offsetof(struct cpu_context, guest_context.t1) */
#define VIRT_CPU_GUEST_T2   336	/* offsetof(struct cpu_context, guest_context.t2) */
#define VIRT_CPU_GUEST_S0   344	/* offsetof(struct cpu_context, guest_context.s0) */
#define VIRT_CPU_GUEST_S1   352	/* offsetof(struct cpu_context, guest_context.s1) */
#define VIRT_CPU_GUEST_A0   360	/* offsetof(struct cpu_context, guest_context.s2) */
#define VIRT_CPU_GUEST_A1   368	/* offsetof(struct cpu_context, guest_context.a1) */
#define VIRT_CPU_GUEST_A2   376	/* offsetof(struct cpu_context, guest_context.a2) */
#define VIRT_CPU_GUEST_A3   384	/* offsetof(struct cpu_context, guest_context.a3) */
#define VIRT_CPU_GUEST_A4   392	/* offsetof(struct cpu_context, guest_context.a4) */
#define VIRT_CPU_GUEST_A5   400	/* offsetof(struct cpu_context, guest_context.a5) */
#define VIRT_CPU_GUEST_A6   408	/* offsetof(struct cpu_context, guest_context.a6) */
#define VIRT_CPU_GUEST_A7   416	/* offsetof(struct cpu_context, guest_context.a6) */
#define VIRT_CPU_GUEST_S2   424	/* offsetof(struct cpu_context, guest_context.s2) */
#define VIRT_CPU_GUEST_S3   432	/* offsetof(struct cpu_context, guest_context.s3) */
#define VIRT_CPU_GUEST_S4   440	/* offsetof(struct cpu_context, guest_context.s4) */
#define VIRT_CPU_GUEST_S5   448	/* offsetof(struct cpu_context, guest_context.s5) */
#define VIRT_CPU_GUEST_S6   456	/* offsetof(struct cpu_context, guest_context.s6) */
#define VIRT_CPU_GUEST_S7   464	/* offsetof(struct cpu_context, guest_context.s7) */
#define VIRT_CPU_GUEST_S8   472	/* offsetof(struct cpu_context, guest_context.s8) */
#define VIRT_CPU_GUEST_S9   480	/* offsetof(struct cpu_context, guest_context.s9) */
#define VIRT_CPU_GUEST_S10  488	/* offsetof(struct cpu_context, guest_context.s10) */
#define VIRT_CPU_GUEST_S11  496	/* offsetof(struct cpu_context, guest_context.s11) */
#define VIRT_CPU_GUEST_T3   504	/* offsetof(struct cpu_context, guest_context.t3) */
#define VIRT_CPU_GUEST_T4   512	/* offsetof(struct cpu_context, guest_context.t4) */
#define VIRT_CPU_GUEST_T5   520	/* offsetof(struct cpu_context, guest_context.t5) */
#define VIRT_CPU_GUEST_T6   528	/* offsetof(struct cpu_context, guest_context.t6) */
#define VIRT_CPU_GUEST_SEPC    536	/* offsetof(struct cpu_context, guest_context.sepc) */
#define VIRT_CPU_GUEST_SSTATUS 544	/* offsetof(struct cpu_context, guest_context.sstatus) */
#define VIRT_CPU_GUEST_HSTATUS 552	/* offsetof(struct cpu_context, guest_context.hstatus) */
#define VIRT_CPU_HOST_SSCRATCH 560	/* offsetof(struct cpu_context, host_scratch) */
#define VIRT_CPU_HOST_STVEC    568	/* offsetof(struct cpu_context, host_stvec) */

#define USER_CPU_S_ZERO 0	/* offsetof(struct cpu_context, host_context.zero) */
#define USER_CPU_S_RA   8	/* offsetof(struct cpu_context, host_context.ra) */
#define USER_CPU_S_SP   16	/* offsetof(struct cpu_context, host_context.sp) */
#define USER_CPU_S_GP   24	/* offsetof(struct cpu_context, host_context.gp) */
#define USER_CPU_S_TP   32	/* offsetof(struct cpu_context, host_context.tp) */
#define USER_CPU_S_T0   40	/* offsetof(struct cpu_context, host_context.t0) */
#define USER_CPU_S_T1   48	/* offsetof(struct cpu_context, host_context.t1) */
#define USER_CPU_S_T2   56	/* offsetof(struct cpu_context, host_context.t2) */
#define USER_CPU_S_S0   64	/* offsetof(struct cpu_context, host_context.s0) */
#define USER_CPU_S_S1   72	/* offsetof(struct cpu_context, host_context.s1) */
#define USER_CPU_S_A0   80	/* offsetof(struct cpu_context, host_context.s2) */
#define USER_CPU_S_A1   88	/* offsetof(struct cpu_context, host_context.a1) */
#define USER_CPU_S_A2   96	/* offsetof(struct cpu_context, host_context.a2) */
#define USER_CPU_S_A3   104	/* offsetof(struct cpu_context, host_context.a3) */
#define USER_CPU_S_A4   112	/* offsetof(struct cpu_context, host_context.a4) */
#define USER_CPU_S_A5   120	/* offsetof(struct cpu_context, host_context.a5) */
#define USER_CPU_S_A6   128	/* offsetof(struct cpu_context, host_context.a6) */
#define USER_CPU_S_A7   136	/* offsetof(struct cpu_context, host_context.a6) */
#define USER_CPU_S_S2   144	/* offsetof(struct cpu_context, host_context.s2) */
#define USER_CPU_S_S3   152	/* offsetof(struct cpu_context, host_context.s3) */
#define USER_CPU_S_S4   160	/* offsetof(struct cpu_context, host_context.s4) */
#define USER_CPU_S_S5   168	/* offsetof(struct cpu_context, host_context.s5) */
#define USER_CPU_S_S6   176	/* offsetof(struct cpu_context, host_context.s6) */
#define USER_CPU_S_S7   184	/* offsetof(struct cpu_context, host_context.s7) */
#define USER_CPU_S_S8   192	/* offsetof(struct cpu_context, host_context.s8) */
#define USER_CPU_S_S9   200	/* offsetof(struct cpu_context, host_context.s9) */
#define USER_CPU_S_S10  208	/* offsetof(struct cpu_context, host_context.s10) */
#define USER_CPU_S_S11  216	/* offsetof(struct cpu_context, host_context.s11) */
#define USER_CPU_S_T3   224	/* offsetof(struct cpu_context, host_context.t3) */
#define USER_CPU_S_T4   232	/* offsetof(struct cpu_context, host_context.t4) */
#define USER_CPU_S_T5   240	/* offsetof(struct cpu_context, host_context.t5) */
#define USER_CPU_S_T6   248	/* offsetof(struct cpu_context, host_context.t6) */
#define USER_CPU_S_SEPC    256	/* offsetof(struct cpu_context, host_context.sepc) */
#define USER_CPU_S_SSTATUS 264	/* offsetof(struct cpu_context, host_context.sstatus) */
#define USER_CPU_S_HSTATUS 272	/* offsetof(struct cpu_context, host_context.hstatus) */

#define USER_CPU_U_ZERO 280	/* offsetof(struct cpu_context, guest_context.zero) */
#define USER_CPU_U_RA   288	/* offsetof(struct cpu_context, guest_context.ra) */
#define USER_CPU_U_SP   296	/* offsetof(struct cpu_context, guest_context.sp) */
#define USER_CPU_U_GP   304	/* offsetof(struct cpu_context, guest_context.gp) */
#define USER_CPU_U_TP   312	/* offsetof(struct cpu_context, guest_context.tp) */
#define USER_CPU_U_T0   320	/* offsetof(struct cpu_context, guest_context.t0) */
#define USER_CPU_U_T1   328	/* offsetof(struct cpu_context, guest_context.t1) */
#define USER_CPU_U_T2   336	/* offsetof(struct cpu_context, guest_context.t2) */
#define USER_CPU_U_S0   344	/* offsetof(struct cpu_context, guest_context.s0) */
#define USER_CPU_U_S1   352	/* offsetof(struct cpu_context, guest_context.s1) */
#define USER_CPU_U_A0   360	/* offsetof(struct cpu_context, guest_context.s2) */
#define USER_CPU_U_A1   368	/* offsetof(struct cpu_context, guest_context.a1) */
#define USER_CPU_U_A2   376	/* offsetof(struct cpu_context, guest_context.a2) */
#define USER_CPU_U_A3   384	/* offsetof(struct cpu_context, guest_context.a3) */
#define USER_CPU_U_A4   392	/* offsetof(struct cpu_context, guest_context.a4) */
#define USER_CPU_U_A5   400	/* offsetof(struct cpu_context, guest_context.a5) */
#define USER_CPU_U_A6   408	/* offsetof(struct cpu_context, guest_context.a6) */
#define USER_CPU_U_A7   416	/* offsetof(struct cpu_context, guest_context.a6) */
#define USER_CPU_U_S2   424	/* offsetof(struct cpu_context, guest_context.s2) */
#define USER_CPU_U_S3   432	/* offsetof(struct cpu_context, guest_context.s3) */
#define USER_CPU_U_S4   440	/* offsetof(struct cpu_context, guest_context.s4) */
#define USER_CPU_U_S5   448	/* offsetof(struct cpu_context, guest_context.s5) */
#define USER_CPU_U_S6   456	/* offsetof(struct cpu_context, guest_context.s6) */
#define USER_CPU_U_S7   464	/* offsetof(struct cpu_context, guest_context.s7) */
#define USER_CPU_U_S8   472	/* offsetof(struct cpu_context, guest_context.s8) */
#define USER_CPU_U_S9   480	/* offsetof(struct cpu_context, guest_context.s9) */
#define USER_CPU_U_S10  488	/* offsetof(struct cpu_context, guest_context.s10) */
#define USER_CPU_U_S11  496	/* offsetof(struct cpu_context, guest_context.s11) */
#define USER_CPU_U_T3   504	/* offsetof(struct cpu_context, guest_context.t3) */
#define USER_CPU_U_T4   512	/* offsetof(struct cpu_context, guest_context.t4) */
#define USER_CPU_U_T5   520	/* offsetof(struct cpu_context, guest_context.t5) */
#define USER_CPU_U_T6   528	/* offsetof(struct cpu_context, guest_context.t6) */
#define USER_CPU_U_SEPC    536	/* offsetof(struct cpu_context, guest_context.sepc) */
#define USER_CPU_U_SSTATUS 544	/* offsetof(struct cpu_context, guest_context.sstatus) */
#define USER_CPU_U_HSTATUS 552	/* offsetof(struct cpu_context, guest_context.hstatus) */
#define USER_CPU_S_SSCRATCH 560	/* offsetof(struct cpu_context, host_scratch) */
#define USER_CPU_S_STVEC    568	/* offsetof(struct cpu_context, host_stvec) */

#endif
