/*
 * Copyright (c) 2024 Beijing Institute of Open Source Chip (BOSC)
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2 or later, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__

#define PT_SIZE 552		/* sizeof(struct pt_regs) */
#define PT_SEPC 0		/* offsetof(struct pt_regs, sepc) */
#define PT_RA 8			/* offsetof(struct pt_regs, ra) */
#define PT_FP 64		/* offsetof(struct pt_regs, s0) */
#define PT_S0 64		/* offsetof(struct pt_regs, s0) */
#define PT_S1 72		/* offsetof(struct pt_regs, s1) */
#define PT_S2 144		/* offsetof(struct pt_regs, s2) */
#define PT_S3 152		/* offsetof(struct pt_regs, s3) */
#define PT_S4 160		/* offsetof(struct pt_regs, s4) */
#define PT_S5 168		/* offsetof(struct pt_regs, s5) */
#define PT_S6 176		/* offsetof(struct pt_regs, s6) */
#define PT_S7 184		/* offsetof(struct pt_regs, s7) */
#define PT_S8 192		/* offsetof(struct pt_regs, s8) */
#define PT_S9 200		/* offsetof(struct pt_regs, s9) */
#define PT_S10 208		/* offsetof(struct pt_regs, s10) */
#define PT_S11 216		/* offsetof(struct pt_regs, s11) */
#define PT_SP 16		/* offsetof(struct pt_regs, sp) */
#define PT_TP 32		/* offsetof(struct pt_regs, tp) */
#define PT_A0 80		/* offsetof(struct pt_regs, a0) */
#define PT_A1 88		/* offsetof(struct pt_regs, a1) */
#define PT_A2 96		/* offsetof(struct pt_regs, a2) */
#define PT_A3 104		/* offsetof(struct pt_regs, a3) */
#define PT_A4 112		/* offsetof(struct pt_regs, a4) */
#define PT_A5 120		/* offsetof(struct pt_regs, a5) */
#define PT_A6 128		/* offsetof(struct pt_regs, a6) */
#define PT_A7 136		/* offsetof(struct pt_regs, a7) */
#define PT_T0 40		/* offsetof(struct pt_regs, t0) */
#define PT_T1 48		/* offsetof(struct pt_regs, t1) */
#define PT_T2 56		/* offsetof(struct pt_regs, t2) */
#define PT_T3 224		/* offsetof(struct pt_regs, t3) */
#define PT_T4 232		/* offsetof(struct pt_regs, t4) */
#define PT_T5 240		/* offsetof(struct pt_regs, t5) */
#define PT_T6 248		/* offsetof(struct pt_regs, t6) */
#define PT_GP 24		/* offsetof(struct pt_regs, gp) */
#define PT_ORIG_A0 280		/* offsetof(struct pt_regs, orig_a0) */
#define PT_SSTATUS 256		/* offsetof(struct pt_regs, sstatus) */
#define PT_SBADADDR 264		/* offsetof(struct pt_regs, sbadaddr) */
#define PT_SCAUSE 272		/* offsetof(struct pt_regs, scause) */
#define PT_HSTATUS 280		/* offsetof(struct pt_regs, hstatus) */
#define PT_SATP 288		/* offsetof(struct pt_regs, satp) */
#define PT_F0  296 /* offsetof(struct pt_regs, f0) */
#define PT_F1  304 /* offsetof(struct pt_regs, f1) */
#define PT_F2  312 /* offsetof(struct pt_regs, f2) */
#define PT_F3  320 /* offsetof(struct pt_regs, f3) */
#define PT_F4  328 /* offsetof(struct pt_regs, f4) */
#define PT_F5  336 /* offsetof(struct pt_regs, f5) */
#define PT_F6  344 /* offsetof(struct pt_regs, f6) */
#define PT_F7  352 /* offsetof(struct pt_regs, f7) */
#define PT_F8  360 /* offsetof(struct pt_regs, f8) */
#define PT_F9  368 /* offsetof(struct pt_regs, f9) */
#define PT_F10 376 /* offsetof(struct pt_regs, f10) */
#define PT_F11 384 /* offsetof(struct pt_regs, f11) */
#define PT_F12 392 /* offsetof(struct pt_regs, f12) */
#define PT_F13 400 /* offsetof(struct pt_regs, f13) */
#define PT_F14 408 /* offsetof(struct pt_regs, f14) */
#define PT_F15 416 /* offsetof(struct pt_regs, f15) */
#define PT_F16 424 /* offsetof(struct pt_regs, f16) */
#define PT_F17 432 /* offsetof(struct pt_regs, f17) */
#define PT_F18 440 /* offsetof(struct pt_regs, f18) */
#define PT_F19 448 /* offsetof(struct pt_regs, f19) */
#define PT_F20 456 /* offsetof(struct pt_regs, f20) */
#define PT_F21 464 /* offsetof(struct pt_regs, f21) */
#define PT_F22 472 /* offsetof(struct pt_regs, f22) */
#define PT_F23 480 /* offsetof(struct pt_regs, f23) */
#define PT_F24 488 /* offsetof(struct pt_regs, f24) */
#define PT_F25 496 /* offsetof(struct pt_regs, f25) */
#define PT_F26 504 /* offsetof(struct pt_regs, f26) */
#define PT_F27 512 /* offsetof(struct pt_regs, f27) */
#define PT_F28 520 /* offsetof(struct pt_regs, f28) */
#define PT_F29 528 /* offsetof(struct pt_regs, f29) */
#define PT_F30 536 /* offsetof(struct pt_regs, f30) */
#define PT_F31 544 /* offsetof(struct pt_regs, f31) */

#define VIRT_CPU_HOST_ZERO 0	/* offsetof(struct cpu_context, host_context.zero) */
#define VIRT_CPU_HOST_RA   8	/* offsetof(struct cpu_context, host_context.ra) */
#define VIRT_CPU_HOST_SP   16	/* offsetof(struct cpu_context, host_context.sp) */
#define VIRT_CPU_HOST_GP   24	/* offsetof(struct cpu_context, host_context.gp) */
#define VIRT_CPU_HOST_TP   32	/* offsetof(struct cpu_context, host_context.tp) */
#define VIRT_CPU_HOST_T0   40	/* offsetof(struct cpu_context, host_context.t0) */
#define VIRT_CPU_HOST_T1   48	/* offsetof(struct cpu_context, host_context.t1) */
#define VIRT_CPU_HOST_T2   56	/* offsetof(struct cpu_context, host_context.t2) */
#define VIRT_CPU_HOST_S0   64	/* offsetof(struct cpu_context, host_context.s0) */
#define VIRT_CPU_HOST_S1   72	/* offsetof(struct cpu_context, host_context.s1) */
#define VIRT_CPU_HOST_A0   80	/* offsetof(struct cpu_context, host_context.s2) */
#define VIRT_CPU_HOST_A1   88	/* offsetof(struct cpu_context, host_context.a1) */
#define VIRT_CPU_HOST_A2   96	/* offsetof(struct cpu_context, host_context.a2) */
#define VIRT_CPU_HOST_A3   104	/* offsetof(struct cpu_context, host_context.a3) */
#define VIRT_CPU_HOST_A4   112	/* offsetof(struct cpu_context, host_context.a4) */
#define VIRT_CPU_HOST_A5   120	/* offsetof(struct cpu_context, host_context.a5) */
#define VIRT_CPU_HOST_A6   128	/* offsetof(struct cpu_context, host_context.a6) */
#define VIRT_CPU_HOST_A7   136	/* offsetof(struct cpu_context, host_context.a6) */
#define VIRT_CPU_HOST_S2   144	/* offsetof(struct cpu_context, host_context.s2) */
#define VIRT_CPU_HOST_S3   152	/* offsetof(struct cpu_context, host_context.s3) */
#define VIRT_CPU_HOST_S4   160	/* offsetof(struct cpu_context, host_context.s4) */
#define VIRT_CPU_HOST_S5   168	/* offsetof(struct cpu_context, host_context.s5) */
#define VIRT_CPU_HOST_S6   176	/* offsetof(struct cpu_context, host_context.s6) */
#define VIRT_CPU_HOST_S7   184	/* offsetof(struct cpu_context, host_context.s7) */
#define VIRT_CPU_HOST_S8   192	/* offsetof(struct cpu_context, host_context.s8) */
#define VIRT_CPU_HOST_S9   200	/* offsetof(struct cpu_context, host_context.s9) */
#define VIRT_CPU_HOST_S10  208	/* offsetof(struct cpu_context, host_context.s10) */
#define VIRT_CPU_HOST_S11  216	/* offsetof(struct cpu_context, host_context.s11) */
#define VIRT_CPU_HOST_T3   224	/* offsetof(struct cpu_context, host_context.t3) */
#define VIRT_CPU_HOST_T4   232	/* offsetof(struct cpu_context, host_context.t4) */
#define VIRT_CPU_HOST_T5   240	/* offsetof(struct cpu_context, host_context.t5) */
#define VIRT_CPU_HOST_T6   248	/* offsetof(struct cpu_context, host_context.t6) */
#define VIRT_CPU_HOST_SEPC    256	/* offsetof(struct cpu_context, host_context.sepc) */
#define VIRT_CPU_HOST_SSTATUS 264	/* offsetof(struct cpu_context, host_context.sstatus) */
#define VIRT_CPU_HOST_HSTATUS 272	/* offsetof(struct cpu_context, host_context.hstatus) */

#define VIRT_CPU_GUEST_ZERO 280	/* offsetof(struct cpu_context, guest_context.zero) */
#define VIRT_CPU_GUEST_RA   288	/* offsetof(struct cpu_context, guest_context.ra) */
#define VIRT_CPU_GUEST_SP   296	/* offsetof(struct cpu_context, guest_context.sp) */
#define VIRT_CPU_GUEST_GP   304	/* offsetof(struct cpu_context, guest_context.gp) */
#define VIRT_CPU_GUEST_TP   312	/* offsetof(struct cpu_context, guest_context.tp) */
#define VIRT_CPU_GUEST_T0   320	/* offsetof(struct cpu_context, guest_context.t0) */
#define VIRT_CPU_GUEST_T1   328	/* offsetof(struct cpu_context, guest_context.t1) */
#define VIRT_CPU_GUEST_T2   336	/* offsetof(struct cpu_context, guest_context.t2) */
#define VIRT_CPU_GUEST_S0   344	/* offsetof(struct cpu_context, guest_context.s0) */
#define VIRT_CPU_GUEST_S1   352	/* offsetof(struct cpu_context, guest_context.s1) */
#define VIRT_CPU_GUEST_A0   360	/* offsetof(struct cpu_context, guest_context.s2) */
#define VIRT_CPU_GUEST_A1   368	/* offsetof(struct cpu_context, guest_context.a1) */
#define VIRT_CPU_GUEST_A2   376	/* offsetof(struct cpu_context, guest_context.a2) */
#define VIRT_CPU_GUEST_A3   384	/* offsetof(struct cpu_context, guest_context.a3) */
#define VIRT_CPU_GUEST_A4   392	/* offsetof(struct cpu_context, guest_context.a4) */
#define VIRT_CPU_GUEST_A5   400	/* offsetof(struct cpu_context, guest_context.a5) */
#define VIRT_CPU_GUEST_A6   408	/* offsetof(struct cpu_context, guest_context.a6) */
#define VIRT_CPU_GUEST_A7   416	/* offsetof(struct cpu_context, guest_context.a6) */
#define VIRT_CPU_GUEST_S2   424	/* offsetof(struct cpu_context, guest_context.s2) */
#define VIRT_CPU_GUEST_S3   432	/* offsetof(struct cpu_context, guest_context.s3) */
#define VIRT_CPU_GUEST_S4   440	/* offsetof(struct cpu_context, guest_context.s4) */
#define VIRT_CPU_GUEST_S5   448	/* offsetof(struct cpu_context, guest_context.s5) */
#define VIRT_CPU_GUEST_S6   456	/* offsetof(struct cpu_context, guest_context.s6) */
#define VIRT_CPU_GUEST_S7   464	/* offsetof(struct cpu_context, guest_context.s7) */
#define VIRT_CPU_GUEST_S8   472	/* offsetof(struct cpu_context, guest_context.s8) */
#define VIRT_CPU_GUEST_S9   480	/* offsetof(struct cpu_context, guest_context.s9) */
#define VIRT_CPU_GUEST_S10  488	/* offsetof(struct cpu_context, guest_context.s10) */
#define VIRT_CPU_GUEST_S11  496	/* offsetof(struct cpu_context, guest_context.s11) */
#define VIRT_CPU_GUEST_T3   504	/* offsetof(struct cpu_context, guest_context.t3) */
#define VIRT_CPU_GUEST_T4   512	/* offsetof(struct cpu_context, guest_context.t4) */
#define VIRT_CPU_GUEST_T5   520	/* offsetof(struct cpu_context, guest_context.t5) */
#define VIRT_CPU_GUEST_T6   528	/* offsetof(struct cpu_context, guest_context.t6) */
#define VIRT_CPU_GUEST_SEPC    536	/* offsetof(struct cpu_context, guest_context.sepc) */
#define VIRT_CPU_GUEST_SSTATUS 544	/* offsetof(struct cpu_context, guest_context.sstatus) */
#define VIRT_CPU_GUEST_HSTATUS 552	/* offsetof(struct cpu_context, guest_context.hstatus) */

#define VIRT_H_F0   560 /* offsetof(struct cpu_context, h_floating.f0) */
#define VIRT_H_F1   568 /* offsetof(struct cpu_context, h_floating.f1) */
#define VIRT_H_F2   576 /* offsetof(struct cpu_context, h_floating.f2) */
#define VIRT_H_F3   584 /* offsetof(struct cpu_context, h_floating.f3) */
#define VIRT_H_F4   592 /* offsetof(struct cpu_context, h_floating.f4) */
#define VIRT_H_F5   600 /* offsetof(struct cpu_context, h_floating.f5) */
#define VIRT_H_F6   608 /* offsetof(struct cpu_context, h_floating.f6) */
#define VIRT_H_F7   616 /* offsetof(struct cpu_context, h_floating.f7) */
#define VIRT_H_F8   624 /* offsetof(struct cpu_context, h_floating.f8) */
#define VIRT_H_F9   632 /* offsetof(struct cpu_context, h_floating.f9) */
#define VIRT_H_F10  640 /* offsetof(struct cpu_context, h_floating.f10) */
#define VIRT_H_F11  648 /* offsetof(struct cpu_context, h_floating.f11) */
#define VIRT_H_F12  656 /* offsetof(struct cpu_context, h_floating.f12) */
#define VIRT_H_F13  664 /* offsetof(struct cpu_context, h_floating.f13) */
#define VIRT_H_F14  672 /* offsetof(struct cpu_context, h_floating.f14) */
#define VIRT_H_F15  680 /* offsetof(struct cpu_context, h_floating.f15) */
#define VIRT_H_F16  688 /* offsetof(struct cpu_context, h_floating.f16) */
#define VIRT_H_F17  696 /* offsetof(struct cpu_context, h_floating.f17) */
#define VIRT_H_F18  704 /* offsetof(struct cpu_context, h_floating.f18) */
#define VIRT_H_F19  712 /* offsetof(struct cpu_context, h_floating.f19) */
#define VIRT_H_F20  720 /* offsetof(struct cpu_context, h_floating.f20) */
#define VIRT_H_F21  728 /* offsetof(struct cpu_context, h_floating.f21) */
#define VIRT_H_F22  736 /* offsetof(struct cpu_context, h_floating.f22) */
#define VIRT_H_F23  744 /* offsetof(struct cpu_context, h_floating.f23) */
#define VIRT_H_F24  752 /* offsetof(struct cpu_context, h_floating.f24) */
#define VIRT_H_F25  760 /* offsetof(struct cpu_context, h_floating.f25) */
#define VIRT_H_F26  768 /* offsetof(struct cpu_context, h_floating.f26) */
#define VIRT_H_F27  776 /* offsetof(struct cpu_context, h_floating.f27) */
#define VIRT_H_F28  784 /* offsetof(struct cpu_context, h_floating.f28) */
#define VIRT_H_F29  792 /* offsetof(struct cpu_context, h_floating.f29) */
#define VIRT_H_F30  800 /* offsetof(struct cpu_context, h_floating.f30) */
#define VIRT_H_F31  808 /* offsetof(struct cpu_context, h_floating.f31) */

#define VIRT_G_F0   816 /* offsetof(struct cpu_context, g_floating.f0) */
#define VIRT_G_F1   824 /* offsetof(struct cpu_context, g_floating.f1) */
#define VIRT_G_F2   832 /* offsetof(struct cpu_context, g_floating.f2) */
#define VIRT_G_F3   840 /* offsetof(struct cpu_context, g_floating.f3) */
#define VIRT_G_F4   848 /* offsetof(struct cpu_context, g_floating.f4) */
#define VIRT_G_F5   856 /* offsetof(struct cpu_context, g_floating.f5) */
#define VIRT_G_F6   864 /* offsetof(struct cpu_context, g_floating.f6) */
#define VIRT_G_F7   872 /* offsetof(struct cpu_context, g_floating.f7) */
#define VIRT_G_F8   880 /* offsetof(struct cpu_context, g_floating.f8) */
#define VIRT_G_F9   888 /* offsetof(struct cpu_context, g_floating.f9) */
#define VIRT_G_F10  896 /* offsetof(struct cpu_context, g_floating.f10) */
#define VIRT_G_F11  904 /* offsetof(struct cpu_context, g_floating.f11) */
#define VIRT_G_F12  912 /* offsetof(struct cpu_context, g_floating.f12) */
#define VIRT_G_F13  920 /* offsetof(struct cpu_context, g_floating.f13) */
#define VIRT_G_F14  928 /* offsetof(struct cpu_context, g_floating.f14) */
#define VIRT_G_F15  936 /* offsetof(struct cpu_context, g_floating.f15) */
#define VIRT_G_F16  944 /* offsetof(struct cpu_context, g_floating.f16) */
#define VIRT_G_F17  952 /* offsetof(struct cpu_context, g_floating.f17) */
#define VIRT_G_F18  960 /* offsetof(struct cpu_context, g_floating.f18) */
#define VIRT_G_F19  968 /* offsetof(struct cpu_context, g_floating.f19) */
#define VIRT_G_F20  976 /* offsetof(struct cpu_context, g_floating.f20) */
#define VIRT_G_F21  984 /* offsetof(struct cpu_context, g_floating.f21) */
#define VIRT_G_F22  992 /* offsetof(struct cpu_context, g_floating.f22) */
#define VIRT_G_F23  1000 /* offsetof(struct cpu_context, g_floating.f23) */
#define VIRT_G_F24  1008 /* offsetof(struct cpu_context, g_floating.f24) */
#define VIRT_G_F25  1016 /* offsetof(struct cpu_context, g_floating.f25) */
#define VIRT_G_F26  1024 /* offsetof(struct cpu_context, g_floating.f26) */
#define VIRT_G_F27  1032 /* offsetof(struct cpu_context, g_floating.f27) */
#define VIRT_G_F28  1040 /* offsetof(struct cpu_context, g_floating.f28) */
#define VIRT_G_F29  1048 /* offsetof(struct cpu_context, g_floating.f29) */
#define VIRT_G_F30  1056 /* offsetof(struct cpu_context, g_floating.f30) */
#define VIRT_G_F31  1064 /* offsetof(struct cpu_context, g_floating.f31) */

#define VIRT_CPU_HOST_SSCRATCH 1072	/* offsetof(struct cpu_context, host_scratch) */
#define VIRT_CPU_HOST_STVEC    1080	/* offsetof(struct cpu_context, host_stvec) */

#define USER_CPU_S_ZERO 0	/* offsetof(struct cpu_context, host_context.zero) */
#define USER_CPU_S_RA   8	/* offsetof(struct cpu_context, host_context.ra) */
#define USER_CPU_S_SP   16	/* offsetof(struct cpu_context, host_context.sp) */
#define USER_CPU_S_GP   24	/* offsetof(struct cpu_context, host_context.gp) */
#define USER_CPU_S_TP   32	/* offsetof(struct cpu_context, host_context.tp) */
#define USER_CPU_S_T0   40	/* offsetof(struct cpu_context, host_context.t0) */
#define USER_CPU_S_T1   48	/* offsetof(struct cpu_context, host_context.t1) */
#define USER_CPU_S_T2   56	/* offsetof(struct cpu_context, host_context.t2) */
#define USER_CPU_S_S0   64	/* offsetof(struct cpu_context, host_context.s0) */
#define USER_CPU_S_S1   72	/* offsetof(struct cpu_context, host_context.s1) */
#define USER_CPU_S_A0   80	/* offsetof(struct cpu_context, host_context.s2) */
#define USER_CPU_S_A1   88	/* offsetof(struct cpu_context, host_context.a1) */
#define USER_CPU_S_A2   96	/* offsetof(struct cpu_context, host_context.a2) */
#define USER_CPU_S_A3   104	/* offsetof(struct cpu_context, host_context.a3) */
#define USER_CPU_S_A4   112	/* offsetof(struct cpu_context, host_context.a4) */
#define USER_CPU_S_A5   120	/* offsetof(struct cpu_context, host_context.a5) */
#define USER_CPU_S_A6   128	/* offsetof(struct cpu_context, host_context.a6) */
#define USER_CPU_S_A7   136	/* offsetof(struct cpu_context, host_context.a6) */
#define USER_CPU_S_S2   144	/* offsetof(struct cpu_context, host_context.s2) */
#define USER_CPU_S_S3   152	/* offsetof(struct cpu_context, host_context.s3) */
#define USER_CPU_S_S4   160	/* offsetof(struct cpu_context, host_context.s4) */
#define USER_CPU_S_S5   168	/* offsetof(struct cpu_context, host_context.s5) */
#define USER_CPU_S_S6   176	/* offsetof(struct cpu_context, host_context.s6) */
#define USER_CPU_S_S7   184	/* offsetof(struct cpu_context, host_context.s7) */
#define USER_CPU_S_S8   192	/* offsetof(struct cpu_context, host_context.s8) */
#define USER_CPU_S_S9   200	/* offsetof(struct cpu_context, host_context.s9) */
#define USER_CPU_S_S10  208	/* offsetof(struct cpu_context, host_context.s10) */
#define USER_CPU_S_S11  216	/* offsetof(struct cpu_context, host_context.s11) */
#define USER_CPU_S_T3   224	/* offsetof(struct cpu_context, host_context.t3) */
#define USER_CPU_S_T4   232	/* offsetof(struct cpu_context, host_context.t4) */
#define USER_CPU_S_T5   240	/* offsetof(struct cpu_context, host_context.t5) */
#define USER_CPU_S_T6   248	/* offsetof(struct cpu_context, host_context.t6) */
#define USER_CPU_S_SEPC    256	/* offsetof(struct cpu_context, host_context.sepc) */
#define USER_CPU_S_SSTATUS 264	/* offsetof(struct cpu_context, host_context.sstatus) */
#define USER_CPU_S_HSTATUS 272	/* offsetof(struct cpu_context, host_context.hstatus) */

#define USER_CPU_U_ZERO 280	/* offsetof(struct cpu_context, guest_context.zero) */
#define USER_CPU_U_RA   288	/* offsetof(struct cpu_context, guest_context.ra) */
#define USER_CPU_U_SP   296	/* offsetof(struct cpu_context, guest_context.sp) */
#define USER_CPU_U_GP   304	/* offsetof(struct cpu_context, guest_context.gp) */
#define USER_CPU_U_TP   312	/* offsetof(struct cpu_context, guest_context.tp) */
#define USER_CPU_U_T0   320	/* offsetof(struct cpu_context, guest_context.t0) */
#define USER_CPU_U_T1   328	/* offsetof(struct cpu_context, guest_context.t1) */
#define USER_CPU_U_T2   336	/* offsetof(struct cpu_context, guest_context.t2) */
#define USER_CPU_U_S0   344	/* offsetof(struct cpu_context, guest_context.s0) */
#define USER_CPU_U_S1   352	/* offsetof(struct cpu_context, guest_context.s1) */
#define USER_CPU_U_A0   360	/* offsetof(struct cpu_context, guest_context.s2) */
#define USER_CPU_U_A1   368	/* offsetof(struct cpu_context, guest_context.a1) */
#define USER_CPU_U_A2   376	/* offsetof(struct cpu_context, guest_context.a2) */
#define USER_CPU_U_A3   384	/* offsetof(struct cpu_context, guest_context.a3) */
#define USER_CPU_U_A4   392	/* offsetof(struct cpu_context, guest_context.a4) */
#define USER_CPU_U_A5   400	/* offsetof(struct cpu_context, guest_context.a5) */
#define USER_CPU_U_A6   408	/* offsetof(struct cpu_context, guest_context.a6) */
#define USER_CPU_U_A7   416	/* offsetof(struct cpu_context, guest_context.a6) */
#define USER_CPU_U_S2   424	/* offsetof(struct cpu_context, guest_context.s2) */
#define USER_CPU_U_S3   432	/* offsetof(struct cpu_context, guest_context.s3) */
#define USER_CPU_U_S4   440	/* offsetof(struct cpu_context, guest_context.s4) */
#define USER_CPU_U_S5   448	/* offsetof(struct cpu_context, guest_context.s5) */
#define USER_CPU_U_S6   456	/* offsetof(struct cpu_context, guest_context.s6) */
#define USER_CPU_U_S7   464	/* offsetof(struct cpu_context, guest_context.s7) */
#define USER_CPU_U_S8   472	/* offsetof(struct cpu_context, guest_context.s8) */
#define USER_CPU_U_S9   480	/* offsetof(struct cpu_context, guest_context.s9) */
#define USER_CPU_U_S10  488	/* offsetof(struct cpu_context, guest_context.s10) */
#define USER_CPU_U_S11  496	/* offsetof(struct cpu_context, guest_context.s11) */
#define USER_CPU_U_T3   504	/* offsetof(struct cpu_context, guest_context.t3) */
#define USER_CPU_U_T4   512	/* offsetof(struct cpu_context, guest_context.t4) */
#define USER_CPU_U_T5   520	/* offsetof(struct cpu_context, guest_context.t5) */
#define USER_CPU_U_T6   528	/* offsetof(struct cpu_context, guest_context.t6) */
#define USER_CPU_U_SEPC    536	/* offsetof(struct cpu_context, guest_context.sepc) */
#define USER_CPU_U_SSTATUS 544	/* offsetof(struct cpu_context, guest_context.sstatus) */
#define USER_CPU_U_HSTATUS 552	/* offsetof(struct cpu_context, guest_context.hstatus) */

#define USER_S_F0   560 /* offsetof(struct cpu_context, s_floating.f0) */
#define USER_S_F1   568 /* offsetof(struct cpu_context, s_floating.f1) */
#define USER_S_F2   576 /* offsetof(struct cpu_context, s_floating.f2) */
#define USER_S_F3   584 /* offsetof(struct cpu_context, s_floating.f3) */
#define USER_S_F4   592 /* offsetof(struct cpu_context, s_floating.f4) */
#define USER_S_F5   600 /* offsetof(struct cpu_context, s_floating.f5) */
#define USER_S_F6   608 /* offsetof(struct cpu_context, s_floating.f6) */
#define USER_S_F7   616 /* offsetof(struct cpu_context, s_floating.f7) */
#define USER_S_F8   624 /* offsetof(struct cpu_context, s_floating.f8) */
#define USER_S_F9   632 /* offsetof(struct cpu_context, s_floating.f9) */
#define USER_S_F10  640 /* offsetof(struct cpu_context, s_floating.f10) */
#define USER_S_F11  648 /* offsetof(struct cpu_context, s_floating.f11) */
#define USER_S_F12  656 /* offsetof(struct cpu_context, s_floating.f12) */
#define USER_S_F13  664 /* offsetof(struct cpu_context, s_floating.f13) */
#define USER_S_F14  672 /* offsetof(struct cpu_context, s_floating.f14) */
#define USER_S_F15  680 /* offsetof(struct cpu_context, s_floating.f15) */
#define USER_S_F16  688 /* offsetof(struct cpu_context, s_floating.f16) */
#define USER_S_F17  696 /* offsetof(struct cpu_context, s_floating.f17) */
#define USER_S_F18  704 /* offsetof(struct cpu_context, s_floating.f18) */
#define USER_S_F19  712 /* offsetof(struct cpu_context, s_floating.f19) */
#define USER_S_F20  720 /* offsetof(struct cpu_context, s_floating.f20) */
#define USER_S_F21  728 /* offsetof(struct cpu_context, s_floating.f21) */
#define USER_S_F22  736 /* offsetof(struct cpu_context, s_floating.f22) */
#define USER_S_F23  744 /* offsetof(struct cpu_context, s_floating.f23) */
#define USER_S_F24  752 /* offsetof(struct cpu_context, s_floating.f24) */
#define USER_S_F25  760 /* offsetof(struct cpu_context, s_floating.f25) */
#define USER_S_F26  768 /* offsetof(struct cpu_context, s_floating.f26) */
#define USER_S_F27  776 /* offsetof(struct cpu_context, s_floating.f27) */
#define USER_S_F28  784 /* offsetof(struct cpu_context, s_floating.f28) */
#define USER_S_F29  792 /* offsetof(struct cpu_context, s_floating.f29) */
#define USER_S_F30  800 /* offsetof(struct cpu_context, s_floating.f30) */
#define USER_S_F31  808 /* offsetof(struct cpu_context, s_floating.f31) */

#define USER_U_F0   816 /* offsetof(struct cpu_context, u_floating.f0) */
#define USER_U_F1   824 /* offsetof(struct cpu_context, u_floating.f1) */
#define USER_U_F2   832 /* offsetof(struct cpu_context, u_floating.f2) */
#define USER_U_F3   840 /* offsetof(struct cpu_context, u_floating.f3) */
#define USER_U_F4   848 /* offsetof(struct cpu_context, u_floating.f4) */
#define USER_U_F5   856 /* offsetof(struct cpu_context, u_floating.f5) */
#define USER_U_F6   864 /* offsetof(struct cpu_context, u_floating.f6) */
#define USER_U_F7   872 /* offsetof(struct cpu_context, u_floating.f7) */
#define USER_U_F8   880 /* offsetof(struct cpu_context, u_floating.f8) */
#define USER_U_F9   888 /* offsetof(struct cpu_context, u_floating.f9) */
#define USER_U_F10  896 /* offsetof(struct cpu_context, u_floating.f10) */
#define USER_U_F11  904 /* offsetof(struct cpu_context, u_floating.f11) */
#define USER_U_F12  912 /* offsetof(struct cpu_context, u_floating.f12) */
#define USER_U_F13  920 /* offsetof(struct cpu_context, u_floating.f13) */
#define USER_U_F14  928 /* offsetof(struct cpu_context, u_floating.f14) */
#define USER_U_F15  936 /* offsetof(struct cpu_context, u_floating.f15) */
#define USER_U_F16  944 /* offsetof(struct cpu_context, u_floating.f16) */
#define USER_U_F17  952 /* offsetof(struct cpu_context, u_floating.f17) */
#define USER_U_F18  960 /* offsetof(struct cpu_context, u_floating.f18) */
#define USER_U_F19  968 /* offsetof(struct cpu_context, u_floating.f19) */
#define USER_U_F20  976 /* offsetof(struct cpu_context, u_floating.f20) */
#define USER_U_F21  984 /* offsetof(struct cpu_context, u_floating.f21) */
#define USER_U_F22  992 /* offsetof(struct cpu_context, u_floating.f22) */
#define USER_U_F23  1000 /* offsetof(struct cpu_context, u_floating.f23) */
#define USER_U_F24  1008 /* offsetof(struct cpu_context, u_floating.f24) */
#define USER_U_F25  1016 /* offsetof(struct cpu_context, u_floating.f25) */
#define USER_U_F26  1024 /* offsetof(struct cpu_context, u_floating.f26) */
#define USER_U_F27  1032 /* offsetof(struct cpu_context, u_floating.f27) */
#define USER_U_F28  1040 /* offsetof(struct cpu_context, u_floating.f28) */
#define USER_U_F29  1048 /* offsetof(struct cpu_context, u_floating.f29) */
#define USER_U_F30  1056 /* offsetof(struct cpu_context, u_floating.f30) */
#define USER_U_F31  1064 /* offsetof(struct cpu_context, u_floating.f31) */

#define USER_CPU_S_SSCRATCH 1072	/* offsetof(struct cpu_context, host_scratch) */
#define USER_CPU_S_STVEC    1080	/* offsetof(struct cpu_context, host_stvec) */

#endif
