#ifndef _REGS_DMAC_AXI_H_
#define _REGS_DMAC_AXI_H_

#define REG_AP_DMAC_AXI0_BASE          (0x30040000)

#define DMAC_AXI_COMMON_REG     0x0
#define DMAC_AXI_CH1_REG        0x100
#define DMAC_AXI_CH2_REG        0x200

#define DMAC_AXI_ID                     0x0
#define DMAC_AXI_COMP_VER               0x08
#define DMAC_AXI_CFG                    0x10
#define DMAC_AXI_CH_EN                  0x18
#define DMAC_AXI_INTR_STATUS            0x30
#define DMAC_AXI_COMMON_INTR_CLEAR      0x38
#define DMAC_AXI_COMMON_STATUS_ENABLE   0x40
#define DMAC_AXI_COMMON_SIGNAL_ENABLE   0x48
#define DMAC_AXI_COMMON_INTR_STATUS     0x50
#define DMAC_AXI_RST_REG                0x58

#define DMAC_AXI_CH_SAR                 0x0
#define DMAC_AXI_CH_DAR                 0x08
#define DMAC_AXI_CH_BLOCK_TS            0x10
#define DMAC_AXI_CH_CTL                 0x18
#define DMAC_AXI_CH_CFG                 0x20
#define DMAC_AXI_CH_LLP                 0x28
#define DMAC_AXI_CH_STATUS              0x30
#define DMAC_AXI_CH_SWHSSRC_REQ         0x38
#define DMAC_AXI_CH_SWHSDST_REQ         0x40
#define DMAC_AXI_CH_BLK_TFR_RESUME_REQ  0x48
#define DMAC_AXI_CH_AXI_ID              0x50
#define DMAC_AXI_CH_AXI_QOS             0x58
#define DMAC_AXI_CH_SSTAT               0x60
#define DMAC_AXI_CH_DSTAT               0x68
#define DMAC_AXI_CH_STATAR              0x70
#define DMAC_AXI_CH_DSTATAR             0x78
#define DMAC_AXI_CH_INTR_STATUS_ENABLE  0x80
#define DMAC_AXI_CH_INTR_STATUS         0x88
#define DMAC_AXI_CH_INTR_SIGNAL_ENABLE  0x90
#define DMAC_AXI_CH_INTR_CLEAR          0x98

#define DMAC_AXI0_COMMON_ID                    REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_ID
#define DMAC_AXI0_COMMON_COMP_VER              REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_COMP_VER
#define DMAC_AXI0_COMMON_CFG                   REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_CFG
#define DMAC_AXI0_COMMON_CH_EN                 REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_CH_EN
#define DMAC_AXI0_COMMON_INTR_STATUS           REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_INTR_STATUS
#define DMAC_AXI0_COMMON_COMMON_INTR_CLEAR     REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_COMMON_INTR_CLEAR
#define DMAC_AXI0_COMMON_COMMON_STATUS_ENABLE  REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_COMMON_STATUS_ENABLE
#define DMAC_AXI0_COMMON_COMMON_SIGNAL_ENABLE  REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_COMMON_SIGNAL_ENABLE
#define DMAC_AXI0_COMMON_COMMON_INTR_STATUS    REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_COMMON_INTR_STATUS
#define DMAC_AXI0_COMMON_RST_REG               REG_AP_DMAC_AXI0_BASE + DMAC_AXI_COMMON_REG + DMAC_AXI_RST_REG

#define DMAC_AXI0_CH1_SAR                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_SAR
#define DMAC_AXI0_CH1_DAR                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_DAR
#define DMAC_AXI0_CH1_BLOCK_TS                 REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_BLOCK_TS
#define DMAC_AXI0_CH1_CTL                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_CTL
#define DMAC_AXI0_CH1_CFG                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_CFG
#define DMAC_AXI0_CH1_LLP                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_LLP
#define DMAC_AXI0_CH1_STATUS                   REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_STATUS
#define DMAC_AXI0_CH1_SWHSSRC_REQ              REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_SWHSSRC_REQ
#define DMAC_AXI0_CH1_SWHSDST_REQ              REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_SWHSDST_REQ
#define DMAC_AXI0_CH1_BLK_TFR_RESUME_REQ       REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_BLK_TFR_RESUME_REQ
#define DMAC_AXI0_CH1_AXI_ID                   REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_AXI_ID
#define DMAC_AXI0_CH1_AXI_QOS                  REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_AXI_QOS
#define DMAC_AXI0_CH1_SSTAT                    REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_SSTAT
#define DMAC_AXI0_CH1_DSTAT                    REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_DSTAT
#define DMAC_AXI0_CH1_STATAR                   REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_STATAR
#define DMAC_AXI0_CH1_DSTATAR                  REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_DSTATAR
#define DMAC_AXI0_CH1_INTR_STATUS_ENABLE       REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_INTR_STATUS_ENABLE
#define DMAC_AXI0_CH1_INTR_STATUS              REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_INTR_STATUS
#define DMAC_AXI0_CH1_INTR_SIGNAL_ENABLE       REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_INTR_SIGNAL_ENABLE
#define DMAC_AXI0_CH1_INTR_CLEAR               REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH1_REG + DMAC_AXI_CH_INTR_CLEAR

#define DMAC_AXI0_CH2_SAR                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_SAR
#define DMAC_AXI0_CH2_DAR                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_DAR
#define DMAC_AXI0_CH2_BLOCK_TS                 REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_BLOCK_TS
#define DMAC_AXI0_CH2_CTL                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_CTL
#define DMAC_AXI0_CH2_CFG                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_CFG
#define DMAC_AXI0_CH2_LLP                      REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_LLP
#define DMAC_AXI0_CH2_STATUS                   REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_STATUS
#define DMAC_AXI0_CH2_SWHSSRC_REQ              REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_SWHSSRC_REQ
#define DMAC_AXI0_CH2_SWHSDST_REQ              REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_SWHSDST_REQ
#define DMAC_AXI0_CH2_BLK_TFR_RESUME_REQ       REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_BLK_TFR_RESUME_REQ
#define DMAC_AXI0_CH2_AXI_ID                   REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_AXI_ID
#define DMAC_AXI0_CH2_AXI_QOS                  REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_AXI_QOS
#define DMAC_AXI0_CH2_SSTAT                    REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_SSTAT
#define DMAC_AXI0_CH2_DSTAT                    REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_DSTAT
#define DMAC_AXI0_CH2_STATAR                   REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_STATAR
#define DMAC_AXI0_CH2_DSTATAR                  REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_DSTATAR
#define DMAC_AXI0_CH2_INTR_STATUS_ENABLE       REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_INTR_STATUS_ENABLE
#define DMAC_AXI0_CH2_INTR_STATUS              REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_INTR_STATUS
#define DMAC_AXI0_CH2_INTR_SIGNAL_ENABLE       REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_INTR_SIGNAL_ENABLE
#define DMAC_AXI0_CH2_INTR_CLEAR               REG_AP_DMAC_AXI0_BASE + DMAC_AXI_CH2_REG + DMAC_AXI_CH_INTR_CLEAR

#endif
