# Copyright (c) 2024 Beijing Institute of Open Source Chip (BOSC)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2 or later, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

obj-y += fdt.o
obj-y += fdt_addresses.o
obj-y += fdt_empty_tree.o
obj-y += fdt_overlay.o
obj-y += fdt_ro.o
obj-y += fdt_rw.o
obj-y += fdt_strerror.o
obj-y += fdt_sw.o
obj-y += fdt_wip.o
