obj-$(CONFIG_USER) += user.o
obj-$(CONFIG_USER) += syscall.o
obj-$(CONFIG_USER) += user_exception.o
obj-$(CONFIG_USER) += user_memory.o
obj-$(CONFIG_USER) += user_pgtable.o
obj-$(CONFIG_USER) += user_vmap.o
obj-$(CONFIG_USER) += user_mode_switch_s.o
