name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install riscv64 toolchain package
      run: export PATH=$PATH:/opt/riscv-gcv-230425/bin

    - name: make
      run: ./build.sh fpga-h
