name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted,linux]

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: |
        export PATH=$PATH:/opt/riscv-gcv-230425/bin
        export CROSS_COMPILE=riscv64-unknown-linux-gnu-
        export ARCH=riscv
        echo "hello" > auto_run.bin
        ./build.sh default

    - name: running
      run: ./build.sh run
