name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted,linux]

    steps:
    - name: set-env
      run: export PATH=$PATH:/opt/riscv-gcv-230425/bin

    - name: make
      run: ./build.sh fpga-h
